blank_issues_enabled: false
contact_links:
  - name: Frequently asked questions
    url: https://staff-scientists-dccn.readthedocs.io
    about: Please check our FAQ before posting an issue.
  - name: Direct contact with the staffscientists
    url: https://mattermost.socsci.ru.nl/dccn/channels/staff-scientists-dccn
    about: You can also reach us on mattermost
